server:
  port: 9090

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db_module25
    username: root
    password: password

  flyway:
    url: jdbc:mysql://localhost:3306/db_module25
    locations: classpath:db/migration
    password: ${spring.r2dbc.password}
    user: ${spring.r2dbc.username}

aws:
  access-key: access-key
  secret-key: secret-key
  region: ru-central1
  s3-bucket-name: bucket-name
  multipart-min-part-size: 5242880
  endpoint: endpoint

jwt:
  password:
    encoder:
      salt: XfL5JQgvODcJTPDqyY69Gy1V6kjtO5km
      iteration: 128000
      key-length: 256
  secret: U2VjcmV0S2V5QnlFcmFTbWF0b3ZGb3JTdHVkeU1vZHVsZTIuNQ==
  expiration: 3600
  issuer: erasmatov

content:
  types: image/png, image/jpg, image/jpeg, image/bmp, image/gif, image/ief, image/pipeg, image/svg+xml, image/tiff
